export const HANDLER_PREFIX = {
  "auth/class-auth-route-handlers.php": "auth",
  "teams/class-teams-route-handlers.php": "teams",
  "chat/class-chat-route-handlers.php": "teams/{teamId}/chat",
  "tasks/class-tasks-route-handlers.php": "teams/{teamId}/tasks",
  "wordpress/class-wp-route-handlers.php": "wordpress",
  "gsc/class-gsc-route-handlers.php": "gsc",
  "ga/class-ga-route-handlers.php": "ga",
  "gmb/class-gmb-route-handlers.php": "gmb",
  "overview/class-overview-route-handlers.php": "overview",
  "dataforseo/class-dataforseo-route-handlers.php": "dataforseo",
  "semrush/class-semrush-route-handlers.php": "semrush",
  "proposal/class-proposal-route-handlers.php": "proposal",
  "seo/class-seo-route-handlers.php": "seo",
  "vertical-benchmark/class-vertical-benchmark-route-handlers.php": "vertical-benchmarks",
  "site-scraper/class-site-scraper-route-handlers.php": "site-scraper",
  "knowledge-model/class-knowledge-model-route-handlers.php": "knowledge-model",
  "images/class-images-route-handlers.php": "images",
  "integrations/class-integrations-route-handlers.php": "integrations",
  "integrations/class-manager-route-handlers.php": null,
};

export const SECTION_LABELS = {
  "getting-started": "Getting started",
  auth: "Authentication",
  teams: "Teams",
  wordpress: "WordPress",
  gsc: "Google Search Console",
  ga: "Google Analytics",
  gmb: "Google Business Profile",
  overview: "Overview",
  dataforseo: "DataForSEO",
  mcp: "DataForSEO MCP",
  semrush: "Semrush",
  proposal: "Proposal",
  seo: "SEO",
  "vertical-benchmarks": "Vertical Benchmarks",
  "site-scraper": "Site Scraper",
  "knowledge-model": "Knowledge Model",
  images: "Images",
  integrations: "Integrations",
  "manager-cloud-settings": "Manager Cloud Settings",
  "manager-wordpress-properties": "Manager WordPress Properties",
  bulk: "Bulk",
  wikipedia: "Wikipedia",
  "entity-maps-image": "Entity Maps",
};

export const SECTION_OVERVIEWS = [
  { sectionId: "auth", slug: "auth/overview", title: "Overview", order: 5 },
  { sectionId: "teams", slug: "teams/overview", title: "Overview", order: 5 },
  { sectionId: "wordpress", slug: "wordpress/overview", title: "Overview", order: 5 },
  { sectionId: "integrations", slug: "integrations/overview", title: "Overview", order: 5 },
];
