/**
 * GSC reporting date presets (re-export from neutral reporting module).
 */

export {
  REPORTING_TRAILING_MONTH_PRESETS as GSC_TRAILING_MONTH_PRESETS,
  type TrailingMonthsPresetId as GscTrailingMonthsPresetId,
  type ReportingComparePresetId as GscReportingComparePresetId,
  type CompareBasis as GscCompareBasis,
  REPORTING_COMPARE_BASIS_OPTIONS as GSC_COMPARE_BASIS_OPTIONS,
  type ReportStructureUi as GscReportStructureUi,
  REPORTING_REPORT_STRUCTURE_OPTIONS as GSC_REPORT_STRUCTURE_OPTIONS,
  REPORTING_LAST_MONTH_PRESETS as GSC_REPORTING_LAST_MONTH_PRESETS,
  isReportingPresetMonthCount as isGscReportingPresetMonthCount,
  formatReportingLastMonthsLabel as formatGscReportingLastMonthsLabel,
  formatReportingDateMenuTriggerLabel as formatGscReportingDateMenuTriggerLabel,
  REPORTING_COMPARE_PRESET_OPTIONS as GSC_REPORTING_COMPARE_PRESET_OPTIONS,
  REPORTING_COMPARE_SPAN_LABEL as GSC_REPORTING_COMPARE_SPAN_LABEL,
  monthSpanFromComparePreset,
  computeTrailingFullMonthsYearOverYearCompareRanges,
  computeCompareRangesForSpan,
  isTrailingMonthsPreset as isGscTrailingMonthsPreset,
  comparePresetPassesRanges as gscComparePresetPassesRanges,
  type ReportingCompareRanges as GscCompareRanges,
  computeMomCompareRanges,
  computeYoyCompareRanges,
  computeTrailingFullMonthsCompareRanges,
  computeCompareRangesForPreset,
  formatLocalYmd,
  formatComparePeriodLabel as formatGscComparePeriodLabel,
  formatReportingRowTitle as formatGscReportingRowTitle,
  formatCompareMonthYearPair as formatGscCompareMonthYearPair,
  formatReportFullDateRange as formatGscReportFullDateRange,
  parseReportingYmd as parseGscYmd,
  TRAILING_MONTH_COUNT_MIN,
  TRAILING_MONTH_COUNT_MAX,
  parseTrailingMonthCount,
  formatTrailingMonthsTriggerLabel,
  formatProgressSpanTriggerLabel,
  formatReportingProgressToolbarTriggerLabel as formatGscProgressToolbarTriggerLabel,
  formatReportingCompareToolbarTriggerLabel as formatGscCompareToolbarTriggerLabel,
  validateReportingCompareFetchRanges as validateGscCompareFetchRanges,
  validateReportingPrimaryFetchRange as validateGscPrimaryFetchRange,
  countCalendarMonthsInRange,
} from "@/lib/reporting/reporting-date-presets";
